### ISSUE TITLE
What the hell is up with the 3rd song?

### ISSUE THREAD

**Issue by PowerMan2206** [brightfyregit/TrollgeSource#1]
When I get to the BF solo part, my health starts draining quickly even though I get all the notes right. I though maybe it was like "oh haha the devs made it so that I gotta miss the notes" but it's not that either. I just die and gotta restart.

Is this the end of the game?

**Comment by brrmason** [comment]
im pretty sure its supposed to drain, maybe if you get all sicks and hold the notes all the way through so  you can keep gaining health i dont really know

**Comment by brightfyregit** [comment]
it's intentional
